In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
warnings.filterwarnings("ignore")

In [3]:
data = pd.read_csv("cat_breeds_dirty.csv", delimiter=";")

In [4]:
data.head()

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
0,Angora,0.25,3.0,female,False,19.0,2.0,white,solid,blue,FALSE,wet,46.0,16.0,France,43.296482,5.369780
1,Angora,0.33,4.0,male,False,19.0,2.5,white,solid,blue,FALSE,wet,48.0,16.0,France,43.611660,3.877710
2,Angora,0.50,NaN,NaN,False,20.0,2.8,what does it mean dominant?,solid,green,I never allow my kitty outside!!!!!,wet,41.0,11.0,France,44.837789,-0.579180
3,Ankora,0.50,NaN,NaN,False,21.0,3.0,white,dirty,blue,FALSE,wet,24.0,8.0,France,43.611660,3.877710
4,Angora,0.50,NaN,NaN,NaN,21.0,3.0,red/cream,tabby,green,FALSE,wet,51.0,10.0,france,48.864716,2.349014

In [5]:
data.describe()

,Age_in_years,Age_in_months,Body_length,Weight,Owner_play_time_minutes,Sleep_time_hours,Latitude,Longitude
count,1072.000000,1066.000000,1077.000000,1077.000000,1082.000000,1062.000000,1042.000000,1042.000000
mean,4.460752,53.778612,43.903435,5.740901,23.176525,15.898305,44.550898,-59.517623
std,3.262166,39.355581,16.240466,9.853438,10.815298,2.656775,4.931844,46.259368
min,-7.666667,-92.000000,10.000000,0.500000,0.000000,8.000000,37.774930,-123.116226
25%,2.330000,28.000000,35.000000,3.900000,15.000000,14.000000,40.714270,-77.036370
50%,4.750000,57.000000,41.000000,5.000000,23.000000,16.000000,43.296482,-74.005970
75%,6.920000,84.000000,51.000000,7.000000,31.000000,18.000000,48.864716,-1.890401
max,11.250000,135.000000,102.000000,320.000000,60.000000,32.000000,53.800755,13.404954

In [6]:
data.tail()

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
1098,Angora,4.170000,50.0,female,True,35.0,2.8,white,solid,amber,TRUE,dry,28.0,14.0,USA,45.52345,-122.676210
1099,Angora,-4.250000,-51.0,male,True,37.0,4.6,white,solid,amber,FALSE,dry,36.0,14.0,France,45.76342,4.834277
1100,Angora,-4.333333,-52.0,female,True,34.0,4.3,white,solid,cute,FALSE,wet,37.0,16.0,USA,42.35843,-71.059770
1101,Angora,-4.333333,-52.0,female,True,35.0,3.8,black,solid,amber,FALSE,wet,30.0,14.0,USA,45.52345,-122.676210
1102,Angora,-4.333333,-52.0,female,True,32.0,2.4,white,solid,blue,FALSE,wet,40.0,14.0,USA,47.60621,-122.332070

In [7]:
data.shape

(1103, 17)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1103 entries, 0 to 1102
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Breed                    991 non-null    str
 1   Age_in_years             1072 non-null   float64
 2   Age_in_months            1066 non-null   float64
 3   Gender                   1036 non-null   str
 4   Neutered_or_spayed       1050 non-null   object
 5   Body_length              1077 non-null   float64
 6   Weight                   1077 non-null   float64
 7   Fur_colour_dominant      1090 non-null   str
 8   Fur_pattern              1055 non-null   str
 9   Eye_colour               1064 non-null   str
 10  Allowed_outdoor          1060 non-null   str
 11  Preferred_food           1082 non-null   str
 12  Owner_play_time_minutes  1082 non-null   float64
 13  Sleep_time_hours         1062 non-null   float64
 14  Country                  1028 non-null   str
 15  Latitude                 1042 non-null   float64
 16  Longitude                1042 non-null   float64
dtypes: float64(8), object(1), str(8)
memory usage: 146.6+ KB

In [9]:
data.describe(include="object")

,Breed,Gender,Neutered_or_spayed,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Country
count,991,1036,1050,1090,1055,1064,1060,1082,1028
unique,12,2,2,7,7,6,4,3,11
top,Ragdoll,male,True,seal,solid,blue,FALSE,wet,USA
freq,374,522,613,292,452,541,960,757,640

In [10]:
pd.isnull(data).sum()

Breed                      112
Age_in_years                31
Age_in_months               37
Gender                      67
Neutered_or_spayed          53
Body_length                 26
Weight                      26
Fur_colour_dominant         13
Fur_pattern                 48
Eye_colour                  39
Allowed_outdoor             43
Preferred_food              21
Owner_play_time_minutes     21
Sleep_time_hours            41
Country                     75
Latitude                    61
Longitude                   61
dtype: int64

In [11]:
data[data["Age_in_years"]<=0]

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
13,Angora,-1.083333,-13.0,male,NaN,28.0,3.20,white,solid,blue,FALSE,wet,35.0,14.0,France,45.763420,4.834277
14,Angora,-1.333333,-16.0,male,NaN,30.0,3.50,red/cream,tabby,blue,FALSE,dry,38.0,20.0,France,48.864716,2.349014
18,Angora,-1.000000,-12.0,male,NaN,31.0,3.50,white,solid,blue,TRUE,wet,42.0,14.0,NaN,43.296482,5.369780
104,Angora,-4.250000,-51.0,male,True,37.0,4.60,white,solid,amber,FALSE,dry,36.0,14.0,France,45.763420,4.834277
105,Angora,-4.333333,-52.0,female,True,34.0,4.30,white,solid,cute,FALSE,wet,37.0,16.0,USA,42.358430,-71.059770
106,Angora,-4.333333,-52.0,female,True,35.0,3.80,black,solid,amber,FALSE,wet,30.0,14.0,USA,45.523450,-122.676210
107,Angora,-4.333333,-52.0,female,True,32.0,2.40,white,solid,blue,FALSE,wet,40.0,14.0,USA,47.606210,-122.332070
108,Angora,-4.416667,-53.0,NaN,False,39.0,4.40,white,solid,blue,FALSE,wet,34.0,16.0,USA,38.895110,-77.036370
109,Angora,-4.500000,-54.0,NaN,True,41.0,5.10,white,solid,amber,FALSE,dry,19.0,14.0,USA,40.714270,-74.005970
110,Angora,-4.500000,-54.0,NaN,False,39.0,4.30,white,solid,blue,FALSE,wet,39.0,16.0,USA,37.774930,-122.419420
111,Angora,-4.583333,-55.0,female,False,35.0,3.40,white,dirty,blue,FALSE,wet,36.0,14.0,USA,40.714270,-74.005970
199,Angora,-7.416667,-89.0,female,True,35.0,3.90,white,solid,blue,TRUE,dry,25.0,19.0,USA,42.358430,-71.059770
200,Angora,-7.416667,-89.0,female,True,34.0,3.30,white,solid,amber,FALSE,wet,32.0,14.0,USA,40.714270,-74.005970
201,Angora,-7.583333,-91.0,male,True,39.0,5.40,white,solid,amber,FALSE,NaN,5.0,14.0,USA,40.714270,-74.005970
202,Angora,-7.583333,-91.0,male,True,40.0,5.50,red/cream,tabby,blue,FALSE,NaN,14.0,14.0,USA,38.895110,-77.036370
203,Angora,-7.666667,-92.0,male,False,36.0,4.90,white,solid,blue,FALSE,NaN,31.0,18.0,USA,38.895110,-77.036370
465,Maine loon,-5.916667,-71.0,female,True,43.0,5.59,black,solid,yellow,FALSE,wet,18.0,NaN,NaN,NaN,NaN
466,Maine coon,-5.916667,-71.0,male,True,56.0,7.00,red/cream,tabby,yellow,FALSE,dry,30.0,NaN,NaN,NaN,NaN
467,Maine coon,-6.000000,-72.0,female,True,59.0,7.56,black,solid,yellow,FALSE,wet,20.0,NaN,NaN,NaN,NaN
468,Maine coon,-6.000000,-72.0,male,False,83.0,10.00,black,solid,green,FALSE,wet,10.0,NaN,NaN,NaN,NaN
469,Maine coon,-6.083333,-73.0,NaN,False,72.0,9.30,brown/chocolate,tabby,green,FALSE,wet,35.0,NaN,NaN,NaN,NaN
470,Maine coon,-6.166667,-74.0,NaN,True,58.0,9.10,black,solid,yellow,TRUE,wet,20.0,NaN,NaN,NaN,NaN
471,Maine coon,-6.166667,-74.0,NaN,False,55.0,5.00,black,solid,yellow,FALSE,dry,31.0,NaN,NaN,NaN,NaN
650,Ragdoll,-1.000000,-12.0,male,True,31.0,4.40,brown/chocolate,colorpoint,blue,TRUE,dry,17.0,15.0,USA,38.895110,-77.036370
651,Ragdoll,-1.000000,-12.0,female,False,26.0,3.90,seal,colorpoint,blue,FALSE,dry,11.0,17.0,USA,38.895110,-77.036370
652,Ragdoll,-1.000000,-12.0,female,False,26.0,4.00,seal,colorpoint,blue,FALSE,wet,17.0,19.0,USA,47.606210,-122.332070
653,Ragdoll,-4.250000,-51.0,male,True,28.0,4.80,red/cream,bicolor,green,FALSE,wet,14.0,13.0,USA,45.523450,-122.676210
654,Ragdoll,-1.083333,-13.0,female,True,21.0,3.80,seal,bicolor,blue,FALSE,wet,22.0,20.0,USA,47.606210,-122.332070
655,ragdoll,-1.166667,-14.0,female,True,24.0,3.90,brown/chocolate,colorpoint,blue,FALSE,wet,34.0,21.0,USA,47.606210,-122.332070
736,Ragdoll,-3.083333,-37.0,female,True,41.0,5.35,brown/chocolate,tortie,green,FALSE,wet,24.0,15.0,USA,41.881832,-87.623177
737,Ragdoll,-3.083333,-37.0,female,False,45.0,4.40,seal,colorpoint,blue,FALSE,wet,25.0,15.0,USA,37.774930,-122.419420
738,rack doll,-3.083333,-37.0,female,NaN,39.0,6.75,seal,colorpoint,blue,FALSE,dry,12.0,15.0,USA,47.606210,-122.332070
739,Ragdoll,-3.166667,-38.0,female,NaN,38.0,5.73,seal,colorpoint,blue,FALSE,wet,2.0,15.0,USA,42.358430,-71.059770
740,Ragdoll,-3.166667,-38.0,male,NaN,43.0,6.56,brown/chocolate,colorpoint,green,FALSE,wet,25.0,15.0,USA,41.881832,-87.623177
741,Ragdoll,-3.166667,-38.0,female,NaN,48.0,6.39,seal,colorpoint,blue,FALSE,wet,32.0,16.0,USA,41.881832,-87.623177
742,Ragdoll,-3.166667,-38.0,female,NaN,47.0,4.38,seal,colorpoint,blue,FALSE,wet,14.0,16.0,USA,40.714270,-74.005970
868,Ragdoll,-6.083333,-73.0,female,True,41.0,6.47,seal,colorpoint,blue,FALSE,dry,18.0,12.0,USA,45.523450,-122.676210
869,Ragdoll,-6.166667,-74.0,male,True,43.0,8.27,brown/chocolate,colorpoint,blue,FALSE,wet,5.0,17.0,UK,52.486244,-1.890401
870,Ragdoll,-6.166667,-74.0,male,False,51.0,7.25,seal,colorpoint,blue,FALSE,wet,15.0,12.0,UK,53.408371,-2.991573
871,Ragdoll,-6.166667,-74.0,female,True,40.0,6.84,seal,bicolor,blue,FALSE,dry,9.0,17.0,UK,51.507351,-0.127758
1099,Angora,-4.250000,-51.0,male,True,37.0,4.60,white,solid,amber,FALSE,dry,36.0,14.0,France,45.763420,4.834277
1100,Angora,-4.333333,-52.0,female,True,34.0,4.30,white,solid,cute,FALSE,wet,37.0,16.0,USA,42.358430,-71.059770
1101,Angora,-4.333333,-52.0,female,True,35.0,3.80,black,solid,amber,FALSE,wet,30.0,14.0,USA,45.523450,-122.676210
1102,Angora,-4.333333,-52.0,female,True,32.0,2.40,white,solid,blue,FALSE,wet,40.0,14.0,USA,47.606210,-122.332070

In [12]:
data = data[data["Age_in_months"] > 0]

In [14]:
data["Age_in_years"] = data["Age_in_years"].fillna(data["Age_in_months"]/12)

In [16]:
data = data.dropna(subset = ["Gender", "Breed", "Neutered_or_spayed", "Allowed_outdoor"])

In [17]:
data.isnull().sum()

Breed                       0
Age_in_years                0
Age_in_months               0
Gender                      0
Neutered_or_spayed          0
Body_length                 8
Weight                      8
Fur_colour_dominant         0
Fur_pattern                 4
Eye_colour                  6
Allowed_outdoor             0
Preferred_food              2
Owner_play_time_minutes    11
Sleep_time_hours           22
Country                    54
Latitude                   45
Longitude                  45
dtype: int64

In [18]:
data.head()

,Breed,Age_in_years,Age_in_months,Gender,Neutered_or_spayed,Body_length,Weight,Fur_colour_dominant,Fur_pattern,Eye_colour,Allowed_outdoor,Preferred_food,Owner_play_time_minutes,Sleep_time_hours,Country,Latitude,Longitude
0,Angora,0.25,3.0,female,False,19.0,2.0,white,solid,blue,FALSE,wet,46.0,16.0,France,43.296482,5.369780
1,Angora,0.33,4.0,male,False,19.0,2.5,white,solid,blue,FALSE,wet,48.0,16.0,France,43.611660,3.877710
26,Angora,1.25,15.0,female,True,26.0,3.4,white,solid,blue,FALSE,wet,25.0,15.0,France,43.296482,5.369780
27,Angora,5.33,64.0,male,True,44.0,4.6,white,solid,blue,TRUE,wet,20.0,16.0,France,44.837789,-0.579180
28,Angora,1.25,15.0,male,True,40.0,3.8,red/cream,tabby,blue,FALSE,wet,35.0,17.0,France,45.763420,4.834277

In [26]:
data["Preferred_food"] = data["Preferred_food"].fillna(data["Preferred_food"].mode()[0])

In [29]:
data["Body_length"] = data["Body_length"].fillna(
    data.groupby(["Breed", "Age_in_years"])["Body_length"]
        .transform("median")
)

In [31]:
data["Weight"] = data["Weight"].fillna(
    data.groupby(["Breed", "Age_in_years"])["Weight"]
        .transform("median")
)

In [34]:
data = data.dropna(subset = ["Body_length", "Weight"])

In [36]:
data["Fur_pattern"] = data["Preferred_food"].fillna(data["Preferred_food"].mode()[0])

In [37]:
mode_by_breed = data.groupby("Breed")["Fur_pattern"].transform(
    lambda s: s.mode()[0]
)

data["Fur_pattern"] = data["Fur_pattern"].fillna(mode_by_breed)

In [38]:
mode_by_breed = data.groupby("Breed")["Fur_pattern"].transform(
    lambda s: s.mode()[0]
)

data["Fur_pattern"] = data["Fur_pattern"].fillna(mode_by_breed)

In [39]:
data["Owner_play_time_minutes"] = data["Owner_play_time_minutes"].fillna(
    data.groupby("Breed")["Owner_play_time_minutes"].transform("median")
)

In [40]:
data["Eye_colour"] = data["Eye_colour"].fillna(
    data.groupby("Breed")["Eye_colour"].transform(lambda s: s.mode()[0])
)

In [42]:
data["Sleep_time_hours"] = data["Sleep_time_hours"].fillna(
    data.groupby("Breed")["Sleep_time_hours"].transform(lambda s: s.mode()[0])
)

In [45]:
data["Country"] = data["Country"].fillna(
    data.groupby(["Latitude", "Longitude"])["Country"].transform("first")
)

In [46]:
data["Latitude"] = data["Latitude"].fillna(
    data.groupby("Country")["Latitude"].transform("median")
)

In [47]:
data["Longitude"] = data["Longitude"].fillna(
    data.groupby("Country")["Longitude"].transform("median")
)

In [52]:
data = data.dropna()

In [53]:
data.isnull().sum()

Breed                      0
Age_in_years               0
Age_in_months              0
Gender                     0
Neutered_or_spayed         0
Body_length                0
Weight                     0
Fur_colour_dominant        0
Fur_pattern                0
Eye_colour                 0
Allowed_outdoor            0
Preferred_food             0
Owner_play_time_minutes    0
Sleep_time_hours           0
Country                    0
Latitude                   0
Longitude                  0
dtype: int64