In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
np.random.seed(43)

In [3]:
X = np.random.rand(10, 7)

In [8]:
mat = pd.DataFrame(X)

In [11]:
mat.head()

          0         1         2         3         4         5         6
0  0.115055  0.609067  0.133391  0.240590  0.327139  0.859137  0.666090
1  0.541162  0.029014  0.733748  0.394950  0.802047  0.254421  0.056885
2  0.866649  0.221029  0.404989  0.316096  0.076663  0.843225  0.848939
3  0.971465  0.385377  0.954488  0.445758  0.669725  0.082500  0.897099
4  0.298004  0.262305  0.005130  0.543203  0.475596  0.636374  0.978204

In [12]:
mat.describe()

,0,1,2,3,4,5,6
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,0.652006,0.518553,0.474003,0.356535,0.445013,0.507201,0.570191
std,0.321990,0.278371,0.281891,0.166663,0.271253,0.328069,0.309687
min,0.115055,0.029014,0.005130,0.104019,0.076663,0.082500,0.056885
25%,0.358793,0.293073,0.325960,0.249332,0.236346,0.218774,0.400499
50%,0.767581,0.632515,0.485159,0.355523,0.407606,0.473322,0.539022
75%,0.898159,0.696581,0.623979,0.516465,0.621193,0.814166,0.835639
max,0.993572,0.910153,0.954488,0.560663,0.896747,0.953040,0.978204

In [13]:
mat.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     float64
 1   1       10 non-null     float64
 2   2       10 non-null     float64
 3   3       10 non-null     float64
 4   4       10 non-null     float64
 5   5       10 non-null     float64
 6   6       10 non-null     float64
dtypes: float64(7)
memory usage: 692.0 bytes